dist: trusty
sudo: enabled
os: linux
language: python
python:
  - "2.7"
  - "3.5"

script:
  - openssl aes-256-cbc -k "${SSH_ENCRYPT_PASSWORD}" -in $TRAVIS_PROJECT_DIR/deployment/vinter.pem.enc -out $TRAVIS_PROJECT_DIR/deployment/vinter.pem -d
  - chmod 600 $TRAVIS_PROJECT_DIR/deployment/vinter.pem

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x $TRAVIS_PROJECT_DIR/deployment/deploy-travis.sh && $TRAVIS_PROJECT_DIR/deployment/deploy-travis.sh
    on:
      branch: development