"""empty message

Revision ID: 84faaeb5e07b
Revises: d0b254ca408a
Create Date: 2019-11-24 17:16:40.968438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84faaeb5e07b'
down_revision = 'd0b254ca408a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('description', table_name='task')
    op.drop_table('task')
    op.drop_index('description', table_name='position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('description', 'position', ['description'], unique=True)
    op.create_table('task',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=2048), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('order', mysql.VARCHAR(length=255), nullable=True),
    sa.CheckConstraint('`active` in (0,1)', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('description', 'task', ['description'], unique=True)
    # ### end Alembic commands ###
