"""empty message

Revision ID: a9a91a917329
Revises: ada43233754c
Create Date: 2019-11-28 09:38:20.024252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9a91a917329'
down_revision = 'ada43233754c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interns', 'tanggal_lahir',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interns', 'tanggal_lahir',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
