"""empty message

Revision ID: ada43233754c
Revises: 5dff7762710d
Create Date: 2019-11-28 09:30:57.940022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada43233754c'
down_revision = '5dff7762710d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interns', sa.Column('desa_kelurahan', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('desa_kelurahan_penempatan', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('jabatan', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('jenis_kelamin', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('jurusan', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('kabupaten', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('kecamatan', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('kecamatan_penempatan', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('kota_kabupaten', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('lama_kerja', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('mulai_tahun', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('nama_ayah', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('nama_ibu', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('nama_perusahaan', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('nik', sa.Integer(), nullable=True))
    op.add_column('interns', sa.Column('provinsi', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('rt', sa.Integer(), nullable=True))
    op.add_column('interns', sa.Column('rw', sa.Integer(), nullable=True))
    op.add_column('interns', sa.Column('status_perkawinan', sa.String(length=255), nullable=True))
    op.add_column('interns', sa.Column('tanggal_lahir', sa.DateTime(), nullable=False))
    op.add_column('interns', sa.Column('tempat_lahir', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interns', 'tempat_lahir')
    op.drop_column('interns', 'tanggal_lahir')
    op.drop_column('interns', 'status_perkawinan')
    op.drop_column('interns', 'rw')
    op.drop_column('interns', 'rt')
    op.drop_column('interns', 'provinsi')
    op.drop_column('interns', 'nik')
    op.drop_column('interns', 'nama_perusahaan')
    op.drop_column('interns', 'nama_ibu')
    op.drop_column('interns', 'nama_ayah')
    op.drop_column('interns', 'mulai_tahun')
    op.drop_column('interns', 'lama_kerja')
    op.drop_column('interns', 'kota_kabupaten')
    op.drop_column('interns', 'kecamatan_penempatan')
    op.drop_column('interns', 'kecamatan')
    op.drop_column('interns', 'kabupaten')
    op.drop_column('interns', 'jurusan')
    op.drop_column('interns', 'jenis_kelamin')
    op.drop_column('interns', 'jabatan')
    op.drop_column('interns', 'desa_kelurahan_penempatan')
    op.drop_column('interns', 'desa_kelurahan')
    # ### end Alembic commands ###
