"""empty message

Revision ID: ec4719cf3683
Revises: 
Create Date: 2019-11-27 22:15:23.583532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4719cf3683'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('image', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'image')
    # ### end Alembic commands ###
